# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: dintels.ru
url: dintels.ru
description: Сайт ООО "Домашние интеллектуальные системы"
author:
  name: Alexey Titov
  email: alexey.titov@dintels.ru

# Grunt handles images and assets.
exclude: ['images', 'styles', 'scripts', 'fonts', 'startup', 'temp',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: true

#blog
permalink:     /blog/:year/:month/:day/:title
paginate_path: "blog/page:num"
paginate: 5